# Generated by Django 6.0.1 on 2026-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
