# Generated by Django 6.0.1 on 2026-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HighSalaryEmployee',
            fields=[
            ],
            options={
                'ordering': ['-salary'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company.employee',),
        ),
    ]
