# Generated by Django 6.0.1 on 2026-04-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('datr_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('join_date', models.DateField()),
            ],
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=200)),
                ('hire_date', models.DateField()),
            ],
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='CustomerProxy',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.customer')),
            ],
            bases=('people.customer',),
        ),
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.employee')),
            ],
            bases=('people.employee',),
        ),
    ]
